# Generated by Django 5.1.2 on 2024-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libManagement', '0004_user_groups_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$7MOZDGNogTp0BWbgX8PBwz$WMTkgPuP9PbGFd7TKAWKtm/IsnXM0qUK4JUphiIO7C4=', max_length=100),
        ),
    ]
