# Generated by Django 5.1.2 on 2024-12-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libManagement', '0007_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$kig8RYDmoqIvvKXCVeQ4V4$ri/Agzmr5Pc4IUBQbVFkTDRIyT+9Cg69ggjUoEojEmk=', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='pbkdf2_sha256$870000$GfsM3i70zsvzMvc3IPwkDl$AeRIXJ3SK3+GXvT7YN2l9UaavdMj2Qbd96VfbS5keyc=', max_length=100, unique=True),
        ),
    ]
