# Generated by Django 5.1.2 on 2024-12-04 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libManagement', '0008_alter_user_password_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrow',
            name='id',
        ),
        migrations.AddField(
            model_name='book',
            name='bookId',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrow',
            name='borrowId',
            field=models.CharField(default=1, max_length=255, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libManagement.book'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$SYFjuXuWdgLOv79flP47U4$fIDBiz/c9lkxgOsgAuFrndL0nkl5qDmPWb5JdF50XU4=', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='pbkdf2_sha256$870000$jjbX77yxaX7wluSHjrfm2O$xDaKrXzISTnyL+wurXo1CQbA4mVuRrSqz09l+leEzJ0=', max_length=100, unique=True),
        ),
    ]
