# Generated by Django 5.1.2 on 2024-12-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libManagement', '0009_remove_borrow_id_book_bookid_borrow_borrowid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='borrow',
            name='unique_active_borrow_per_user',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$IDevAcWfCSWF8KSxpNwddg$q/DG84Ym1G+Du1w8s9T/6yle0EF9jjrpXt530EUFZhU=', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='pbkdf2_sha256$870000$vJBHWOOQL2rfN1tRwyD3IV$KXK8I4QF7kSaGB/cb7IWveg4ZvDeSTZh2auC5XvmD8Q=', max_length=100, unique=True),
        ),
    ]
