# Generated by Django 5.1.2 on 2024-12-04 05:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libManagement', '0010_remove_borrow_unique_active_borrow_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='borrowId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$Id6zB6uJt8bXqVXoYtAJfI$OO+nXX5VvLl2vdZqVpnK9h86xzzwrwbeLS0dltGfCv0=', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='pbkdf2_sha256$870000$skKuP3JHdbmu63oBgaugSv$Bn+Siq7AyVL4pHpd3vmJhsyBSnGWQAIHuRRy7dgYZiQ=', max_length=100, unique=True),
        ),
        migrations.AddConstraint(
            model_name='borrow',
            constraint=models.UniqueConstraint(condition=models.Q(('borrow_returned__isnull', True)), fields=('book', 'user'), name='unique_active_borrow_per_user'),
        ),
    ]
